version: "3.7"

services:
  postgres:
    image: postgres:11.3-alpine
    ports:
      - 5432:5432
  streamer:
    build:
      context: ./streamer
      dockerfile: Dockerfile
    volumes:
      - ./streamer/run.sh:/run.sh
    ports:
      - 1935:1935
      - 8085:8080
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
